### PR TITLE
add initial appveyor config

### PR DESCRIPTION
**Pull request by steffengy**
@cznic 
Just letting this serve as first PR test.
If the config is right, tests should be run on this directly and the status should be shown below at the merging section.

### CODE REVIEW

**Review by cznic — APPROVED** [review]
LGTM, thanks. Please merge.

**Comment by cznic** [comment]
It works, all-green ;-)

Thank you!

**Comment by steffengy** [comment]
Great let me know when sqlite2go is ready for a prepared PR.
(I'll disable windows tests until the first windows PR though, since it cannot work until quite a few more PRs will land)

**Comment by cznic** [comment]
> Great let me know when sqlite2go is ready for a prepared PR.

Will do.

**Pull request merged**
